# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestGOLO():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_gOLO(self):
    self.driver.get("https://www.golo.com/pages/resources-myg1")
    self.driver.set_window_size(1417, 773)
    self.driver.find_element(By.CSS_SELECTOR, "#navlink-item-shop > .ml-xl-1").click()
    self.driver.find_element(By.ID, "desktop-release-reorders-new-exclusive-golo-products39578003669055").click()
    self.driver.find_element(By.CSS_SELECTOR, "#release-reorders-new-exclusive-golo-products .shop-mygolo-product-card__qty-button-wrapper > .col-12").click()
    self.driver.find_element(By.CSS_SELECTOR, ".button--continue-shopping").click()
    self.driver.find_element(By.CSS_SELECTOR, "#aerotrainer-new-11-29-22-exclusive-golo-products .icon:nth-child(4)").click()
    self.driver.find_element(By.ID, "aerotrainer-new-11-29-22").send_keys("1")
    self.driver.find_element(By.CSS_SELECTOR, "#aerotrainer-new-11-29-22-exclusive-golo-products .shop-mygolo-product-card__button--atc").click()
    self.driver.find_element(By.CSS_SELECTOR, ".button--continue-shopping").click()
    self.driver.find_element(By.CSS_SELECTOR, "#avocado-oil-1-super-foods-essentials .icon:nth-child(4)").click()
    self.driver.find_element(By.ID, "avocado-oil-1").send_keys("1")
    self.driver.find_element(By.CSS_SELECTOR, "#avocado-oil-1-super-foods-essentials .icon:nth-child(4)").click()
    self.driver.find_element(By.ID, "avocado-oil-1").send_keys("2")
    self.driver.find_element(By.CSS_SELECTOR, "#avocado-oil-1-super-foods-essentials .shop-mygolo-product-card__button--atc").click()
    self.driver.find_element(By.CSS_SELECTOR, ".button--continue-shopping").click()
    self.driver.find_element(By.CSS_SELECTOR, "#perfect-5-additional-products .icon:nth-child(4)").click()
    self.driver.find_element(By.ID, "perfect-5").send_keys("1")
    self.driver.find_element(By.CSS_SELECTOR, "#perfect-5-additional-products .shop-mygolo-product-card__button--atc").click()
    self.driver.find_element(By.CSS_SELECTOR, ".modal-cart-button--wrapper > .col-12").click()
    element = self.driver.find_element(By.NAME, "checkout")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.NAME, "checkout").click()
    self.driver.find_element(By.ID, "coupon").click()
    self.driver.find_element(By.ID, "checkout_reduction_code").click()
    self.driver.find_element(By.ID, "checkout_reduction_code").send_keys("testorder")
    self.driver.find_element(By.CSS_SELECTOR, ".icon-svg:nth-child(4)").click()
    self.driver.find_element(By.ID, "continue_button").click()
    self.driver.find_element(By.ID, "btn-proceed-address").click()
    self.driver.find_element(By.CSS_SELECTOR, "#continue_button > .btn__content").click()
    self.driver.execute_script("window.scrollTo(0,2)")
    self.driver.find_element(By.ID, "continue_button").click()
    element = self.driver.find_element(By.ID, "continue_button")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
  
